
import { ReactNode } from 'react'
import Head from 'next/head'
import { ChevronDown } from 'react-bootstrap-icons';
import Link from 'next/link';
import { useRouter } from 'next/router';

const PanelTemplate: React.FC<{
    children: ReactNode,
    tabName: string
}> = ({ children, tabName }) => {
    const router = useRouter();
    const currentPath = router.pathname;

    return (
        <>
            <Head>
                <title>ZanaatHan Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='panel-page'>
                <nav className='panel-nav'>
                    <h2 className='nav-logo'>Zanaat.Han Admin</h2>
                    <ul>
                        <li className={`${currentPath === '/panel/onay-bekleyenler' ? 'active' : ''}`}>
                            <Link href={'/panel/onay-bekleyenler'}>Onay bekleyenler</Link>
                        </li>
                        <li className={`${currentPath === '/panel/raporlar' ? 'active' : ''}`}>
                            <Link href={'/panel/raporlar'}>Raporlar</Link>
                        </li>
                        <li className={`${currentPath === '/panel/kullanicilar' ? 'active' : ''}`}>
                            <Link href={'/panel/kullanicilar'}>Kullanıcıları yönet</Link>
                        </li>
                        <li className={`${currentPath === '/panel/admin' ? 'active' : ''}`}>
                            <Link href={'/panel/admin'}>Hesap</Link>
                        </li>
                    </ul>
                </nav>
                <div className='panel'>
                    <header>
                        <h2 className='tab-name'>{tabName}</h2>
                        <div className="admin-container">
                            <span>İrşatAkdeniz</span>
                            <ChevronDown />
                        </div>
                    </header>
                    <main>
                        {children}
                    </main>
                </div>
            </div>
        </>
    );
}

export default PanelTemplate;