import Head from "next/head";
import PanelTemplate from "./components/template";



export default function AdminLogin() {
    return (
        <>
            <Head>
                <title>ZanaatHan Admin Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="admin-login-page">
                <h1>Zanaat.Han</h1>
                <form className="login-form" onSubmit={() => { }}>
                    <h3>Admin Girişi</h3>
                    <input type="text" name="username" placeholder="Admin adı" />
                    <input type="text" name="password" placeholder="Şifre" />
                    <button type="submit">Giriş</button>
                    {/*<span className="warning"></span>*/}
                </form>
            </div>
        </>
    )
}
